package p2p.model;

import java.sql.Timestamp;
import java.util.Objects;

/**
 * Domain model representing a registered PeerLink user.
 *
 * <p>The {@code password} field is expected to store a BCrypt hash, never a plaintext
 * value. The {@link #toString()} method intentionally omits it to prevent accidental
 * exposure in logs.</p>
 *
 * <p>Equality and hashing are based solely on {@link #id} (the surrogate primary key),
 * consistent with JPA and standard domain-model conventions.</p>
 */
public class User {

    // -----------------------------------------------------------------------
    // Fields
    // -----------------------------------------------------------------------

    /** Surrogate primary key, auto-generated by the database. */
    private Long id;

    /** Unique, case-sensitive login handle. */
    private String username;

    /** Unique e-mail address used for account verification and notifications. */
    private String email;

    /**
     * BCrypt-hashed password.
     * <strong>Never store or compare plaintext passwords through this field.</strong>
     */
    private String password;

    /**
     * Authorisation role, e.g. {@code "USER"}, {@code "ADMIN"}.
     * Defaults to {@code "USER"} in the no-arg constructor.
     */
    private String role;

    /** Whether the user has completed e-mail verification. */
    private Boolean isVerified;

    /** UTC timestamp of account creation, set once at insert time. */
    private Timestamp createdAt;

    /** UTC timestamp of the most recent successful login; {@code null} if never logged in. */
    private Timestamp lastLogin;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /**
     * No-arg constructor required for JDBC row-mapping and serialisation frameworks.
     * Sets safe defaults: {@code role = "USER"}, {@code isVerified = false}.
     */
    public User() {
        this.role       = "USER";
        this.isVerified = false;
    }

    /**
     * Convenience constructor for creating a new, unverified user before persisting.
     * {@code id}, {@code createdAt}, and {@code lastLogin} are left {@code null}
     * and are expected to be assigned by the database / repository layer.
     *
     * @param username non-null, unique login handle
     * @param email    non-null, unique e-mail address
     * @param password BCrypt hash of the user's password
     * @param role     authorisation role (e.g. {@code "USER"})
     */
    public User(String username, String email, String password, String role) {
        this.username   = username;
        this.email      = email;
        this.password   = password;
        this.role       = (role != null) ? role : "USER";
        this.isVerified = false;
    }

    /**
     * Full constructor — typically used when hydrating a row from the database.
     *
     * @param id         surrogate primary key
     * @param username   login handle
     * @param email      e-mail address
     * @param password   BCrypt-hashed password
     * @param role       authorisation role
     * @param isVerified e-mail verification status
     * @param createdAt  account creation timestamp
     * @param lastLogin  most recent login timestamp, may be {@code null}
     */
    public User(Long id, String username, String email, String password,
                String role, Boolean isVerified,
                Timestamp createdAt, Timestamp lastLogin) {
        this.id         = id;
        this.username   = username;
        this.email      = email;
        this.password   = password;
        this.role       = role;
        this.isVerified = isVerified;
        this.createdAt  = createdAt;
        this.lastLogin  = lastLogin;
    }

    // -----------------------------------------------------------------------
    // Getters & Setters
    // -----------------------------------------------------------------------

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /** Returns the BCrypt-hashed password. Never log or expose this value directly. */
    public String getPassword() {
        return password;
    }

    /** Accepts a BCrypt hash. Callers must hash the plaintext before invoking this method. */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(Timestamp lastLogin) {
        this.lastLogin = lastLogin;
    }

    // -----------------------------------------------------------------------
    // equals & hashCode  (identity based on surrogate primary key)
    // -----------------------------------------------------------------------

    /**
     * Two {@code User} instances are equal when both have a non-null {@code id}
     * and those IDs are equal.  Transient (unsaved) users with a {@code null} id
     * are never equal to any other instance, including themselves — this mirrors
     * standard JPA entity equality semantics and avoids surprises in collections.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;
        User other = (User) o;
        // Unsaved entities (id == null) are never equal to anything else
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        // Fixed constant for unsaved entities (id == null) keeps hash stable
        // before and after persistence, consistent with equals contract.
        return Objects.hashCode(id);
    }

    // -----------------------------------------------------------------------
    // toString
    // -----------------------------------------------------------------------

    /**
     * Returns a human-readable representation of the user.
     * <strong>The {@code password} field is deliberately excluded</strong>
     * to prevent BCrypt hashes from leaking into application logs.
     */
    @Override
    public String toString() {
        return "User{" +
               "id="         + id         +
               ", username='" + username  + '\'' +
               ", email='"    + email     + '\'' +
               ", role='"     + role      + '\'' +
               ", isVerified=" + isVerified +
               ", createdAt=" + createdAt +
               ", lastLogin=" + lastLogin +
               '}';
    }
}
